apiVersion: apps/v1
kind: Deployment
metadata:
  name: fueltrack-deployment
  namespace: fueltrack # namespace specified here
  labels:
    app: fueltrack
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fueltrack
  template:
    metadata:
      labels:
        app: fueltrack
    spec:
      volumes:
      - name: fueltrack-pv
        persistentVolumeClaim:
          claimName: fueltrack-pvc
      containers:
      - name: fueltrack
        image: hasino2258/fueltrack:2.1
        ports:
        - containerPort: 9001
        envFrom:
        - configMapRef:
            name: fueltrack-configmap
        volumeMounts:
        - name: fueltrack-pv
          mountPath: /var/www/html/storage
























# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: fueltrack-deployment
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: fueltrack
#   template:
#     metadata:
#       labels:
#         app: fueltrack
#     spec:
#       containers:
#       - name: fueltrack
#         image: hasino2258/fueltrack:v2
#         ports:
#         - containerPort: 9001
#         envFrom:
#         - configMapRef:
#             name: fueltrack-configmap
#             env:
#             - name: MYSQL_HOST
#               value: mysql-service
#             - name: MYSQL_PORT
#               value: 3306
#             - name: MYSQL_USER
#               valueFrom:
#                 secretKeyRef:
#                   name: mysql-secret
#                   key: username
#             - name: MYSQL_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: mysql-secret
#                   key: password


---
apiVersion: v1
kind: Service
metadata:
  name: fueltrack-service
spec:
  selector:
    app: fueltrack
  type: LoadBalancer
  ports:
  - name: http
    # - protocol: tcp
    port: 80
    targetPort: 9001
    # nodePort: 30000











