apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: fueltrack # namespace specified here

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
