apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: fueltrack # namespace specified here

spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mysql
